//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.12 at 08:50:51 PM NPT 
//


package com.rss.foxSports.Soccer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rss.foxSports.Soccer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RssChannelImage_QNAME = new QName("", "image");
    private final static QName _RssChannelItem_QNAME = new QName("", "item");
    private final static QName _RssChannelLink_QNAME = new QName("", "link");
    private final static QName _RssChannelDescription_QNAME = new QName("", "description");
    private final static QName _RssChannelLanguage_QNAME = new QName("", "language");
    private final static QName _RssChannelTitle_QNAME = new QName("", "title");
    private final static QName _RssChannelPubDate_QNAME = new QName("", "pubDate");
    private final static QName _RssChannelTtl_QNAME = new QName("", "ttl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rss.foxSports.Soccer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rss }
     * 
     */
    public Rss createRss() {
        return new Rss();
    }

    /**
     * Create an instance of {@link Rss.Channel }
     * 
     */
    public Rss.Channel createRssChannel() {
        return new Rss.Channel();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item }
     * 
     */
    public Rss.Channel.Item createRssChannelItem() {
        return new Rss.Channel.Item();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Rss.Channel.Image }
     * 
     */
    public Rss.Channel.Image createRssChannelImage() {
        return new Rss.Channel.Image();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Enclosure }
     * 
     */
    public Rss.Channel.Item.Enclosure createRssChannelItemEnclosure() {
        return new Rss.Channel.Item.Enclosure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rss.Channel.Image }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "image", scope = Rss.Channel.class)
    public JAXBElement<Rss.Channel.Image> createRssChannelImage(Rss.Channel.Image value) {
        return new JAXBElement<Rss.Channel.Image>(_RssChannelImage_QNAME, Rss.Channel.Image.class, Rss.Channel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rss.Channel.Item }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "item", scope = Rss.Channel.class)
    public JAXBElement<Rss.Channel.Item> createRssChannelItem(Rss.Channel.Item value) {
        return new JAXBElement<Rss.Channel.Item>(_RssChannelItem_QNAME, Rss.Channel.Item.class, Rss.Channel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "link", scope = Rss.Channel.class)
    public JAXBElement<String> createRssChannelLink(String value) {
        return new JAXBElement<String>(_RssChannelLink_QNAME, String.class, Rss.Channel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description", scope = Rss.Channel.class)
    public JAXBElement<String> createRssChannelDescription(String value) {
        return new JAXBElement<String>(_RssChannelDescription_QNAME, String.class, Rss.Channel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language", scope = Rss.Channel.class)
    public JAXBElement<String> createRssChannelLanguage(String value) {
        return new JAXBElement<String>(_RssChannelLanguage_QNAME, String.class, Rss.Channel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = Rss.Channel.class)
    public JAXBElement<String> createRssChannelTitle(String value) {
        return new JAXBElement<String>(_RssChannelTitle_QNAME, String.class, Rss.Channel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pubDate", scope = Rss.Channel.class)
    public JAXBElement<String> createRssChannelPubDate(String value) {
        return new JAXBElement<String>(_RssChannelPubDate_QNAME, String.class, Rss.Channel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ttl", scope = Rss.Channel.class)
    public JAXBElement<Short> createRssChannelTtl(Short value) {
        return new JAXBElement<Short>(_RssChannelTtl_QNAME, Short.class, Rss.Channel.class, value);
    }

}
