//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.12 at 08:50:51 PM NPT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2005/Atom")
package com.rss.foxSports.Soccer;
